module ArkEmail
  module Internal
    class OffsetPagination[Elem]
      include ArkEmail::Internal::Type::BasePage[Elem]

      attr_accessor data: Data

      def inspect: -> String

      type data =
        { pagination: Data::Pagination, tenants: ::Array[::Hash[Symbol, top]] }
      class Data < ArkEmail::Internal::Type::BaseModel
        attr_reader pagination: Data::Pagination?

        def pagination=: (Data::Pagination) -> Data::Pagination

        attr_reader tenants: ::Array[::Hash[Symbol, top]]?

        def tenants=: (
          ::Array[::Hash[Symbol, top]]
        ) -> ::Array[::Hash[Symbol, top]]

        def initialize: (
          ?pagination: Data::Pagination,
          ?tenants: ::Array[::Hash[Symbol, top]]
        ) -> void

        def to_hash: -> {
          pagination: Data::Pagination,
          tenants: ::Array[::Hash[Symbol, top]]
        }

        type pagination =
          { has_more: bool, limit: Integer, offset: Integer, total: Integer }

        class Pagination < ArkEmail::Internal::Type::BaseModel
          attr_reader has_more: bool?

          def has_more=: (bool) -> bool

          attr_reader limit: Integer?

          def limit=: (Integer) -> Integer

          attr_reader offset: Integer?

          def offset=: (Integer) -> Integer

          attr_reader total: Integer?

          def total=: (Integer) -> Integer

          def initialize: (
            ?has_more: bool,
            ?limit: Integer,
            ?offset: Integer,
            ?total: Integer
          ) -> void

          def to_hash: -> {
            has_more: bool,
            limit: Integer,
            offset: Integer,
            total: Integer
          }
        end
      end
    end
  end
end
