module Ark
  module Resources
    class Domains
      def create: (
        name: String,
        ?request_options: Ark::request_opts
      ) -> Ark::Models::DomainCreateResponse

      def retrieve: (
        String domain_id,
        ?request_options: Ark::request_opts
      ) -> Ark::Models::DomainRetrieveResponse

      def list: (
        ?request_options: Ark::request_opts
      ) -> Ark::Models::DomainListResponse

      def delete: (
        String domain_id,
        ?request_options: Ark::request_opts
      ) -> Ark::Models::DomainDeleteResponse

      def verify: (
        String domain_id,
        ?request_options: Ark::request_opts
      ) -> Ark::Models::DomainVerifyResponse

      def initialize: (client: Ark::Client) -> void
    end
  end
end
