module Ark
  module Resources
    class Tracking
      def create: (
        domain_id: String,
        name: String,
        ?ssl_enabled: bool,
        ?track_clicks: bool,
        ?track_opens: bool,
        ?request_options: Ark::request_opts
      ) -> Ark::Models::TrackingCreateResponse

      def retrieve: (
        String tracking_id,
        ?request_options: Ark::request_opts
      ) -> Ark::Models::TrackingRetrieveResponse

      def update: (
        String tracking_id,
        ?excluded_click_domains: String,
        ?ssl_enabled: bool,
        ?track_clicks: bool,
        ?track_opens: bool,
        ?request_options: Ark::request_opts
      ) -> Ark::Models::TrackingUpdateResponse

      def list: (
        ?request_options: Ark::request_opts
      ) -> Ark::Models::TrackingListResponse

      def delete: (
        String tracking_id,
        ?request_options: Ark::request_opts
      ) -> Ark::Models::TrackingDeleteResponse

      def verify: (
        String tracking_id,
        ?request_options: Ark::request_opts
      ) -> Ark::Models::TrackingVerifyResponse

      def initialize: (client: Ark::Client) -> void
    end
  end
end
