module Ark
  module Internal
    class PageNumberPagination[Elem]
      include Ark::Internal::Type::BasePage[Elem]

      attr_accessor data: Data

      def inspect: -> String

      type data = { pagination: Data::Pagination }
      class Data < Ark::Internal::Type::BaseModel
        attr_reader pagination: Data::Pagination?

        def pagination=: (Data::Pagination) -> Data::Pagination

        def initialize: (?pagination: Data::Pagination) -> void

        def to_hash: -> { pagination: Data::Pagination }

        type pagination = { page: Integer, total_pages: Integer }

        class Pagination < Ark::Internal::Type::BaseModel
          attr_reader page: Integer?

          def page=: (Integer) -> Integer

          attr_reader total_pages: Integer?

          def total_pages=: (Integer) -> Integer

          def initialize: (?page: Integer, ?total_pages: Integer) -> void

          def to_hash: -> { page: Integer, total_pages: Integer }
        end
      end
    end
  end
end
