module Ark
  module Internal
    class PageNumberPagination[Elem]
      include Ark::Internal::Type::BasePage[Elem]

      attr_accessor data: ::Array[Elem]?

      attr_accessor page: Integer

      attr_accessor per_page: Integer

      attr_accessor total: Integer

      attr_accessor total_pages: Integer

      attr_accessor meta: Meta

      def inspect: -> String

      type meta = { request_id: String }
      class Meta < Ark::Internal::Type::BaseModel
        attr_reader request_id: String?

        def request_id=: (String) -> String

        def initialize: (?request_id: String) -> void

        def to_hash: -> { request_id: String }
      end
    end
  end
end
