module Ark
  module Internal
    class SuppressionsPage[Elem]
      include Ark::Internal::Type::BasePage[Elem]

      attr_accessor success: bool

      attr_accessor data: Data

      attr_accessor meta: Meta

      def inspect: -> String

      type data =
        {
          pagination: Data::Pagination,
          suppressions: ::Array[::Hash[Symbol, top]]
        }
      class Data < Ark::Internal::Type::BaseModel
        attr_accessor pagination: Data::Pagination

        attr_accessor suppressions: ::Array[::Hash[Symbol, top]]

        def initialize: (
          pagination: Data::Pagination,
          suppressions: ::Array[::Hash[Symbol, top]]
        ) -> void

        def to_hash: -> {
          pagination: Data::Pagination,
          suppressions: ::Array[::Hash[Symbol, top]]
        }

        type pagination =
          {
            page: Integer,
            per_page: Integer,
            total: Integer,
            total_pages: Integer
          }

        class Pagination < Ark::Internal::Type::BaseModel
          attr_accessor page: Integer

          attr_accessor per_page: Integer

          attr_accessor total: Integer

          attr_accessor total_pages: Integer

          def initialize: (
            page: Integer,
            per_page: Integer,
            total: Integer,
            total_pages: Integer
          ) -> void

          def to_hash: -> {
            page: Integer,
            per_page: Integer,
            total: Integer,
            total_pages: Integer
          }
        end
      end

      type meta = { request_id: String }
      class Meta < Ark::Internal::Type::BaseModel
        attr_reader request_id: String?

        def request_id=: (String) -> String

        def initialize: (?request_id: String) -> void

        def to_hash: -> { request_id: String }
      end
    end
  end
end
