module Ark
  module Internal
    class SuppressionsPagination[Elem]
      include Ark::Internal::Type::BasePage[Elem]

      attr_accessor data: Data

      def inspect: -> String

      type data =
        {
          pagination: Data::Pagination,
          suppressions: ::Array[Data::Suppression]
        }
      class Data < Ark::Internal::Type::BaseModel
        attr_reader pagination: Data::Pagination?

        def pagination=: (Data::Pagination) -> Data::Pagination

        attr_reader suppressions: ::Array[Data::Suppression]?

        def suppressions=: (
          ::Array[Data::Suppression]
        ) -> ::Array[Data::Suppression]

        def initialize: (
          ?pagination: Data::Pagination,
          ?suppressions: ::Array[Data::Suppression]
        ) -> void

        def to_hash: -> {
          pagination: Data::Pagination,
          suppressions: ::Array[Data::Suppression]
        }

        type pagination = { page: Integer, total_pages: Integer }

        class Pagination < Ark::Internal::Type::BaseModel
          attr_reader page: Integer?

          def page=: (Integer) -> Integer

          attr_reader total_pages: Integer?

          def total_pages=: (Integer) -> Integer

          def initialize: (?page: Integer, ?total_pages: Integer) -> void

          def to_hash: -> { page: Integer, total_pages: Integer }
        end

        type suppression =
          { id: String, address: String, created_at: Time, reason: String }

        class Suppression < Ark::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor address: String

          attr_accessor created_at: Time

          attr_reader reason: String?

          def reason=: (String) -> String

          def initialize: (
            id: String,
            address: String,
            created_at: Time,
            ?reason: String
          ) -> void

          def to_hash: -> {
            id: String,
            address: String,
            created_at: Time,
            reason: String
          }
        end
      end
    end
  end
end
