module ArkEmail
  module Models
    module Platform
      type webhook_retrieve_delivery_params =
        { delivery_id: String } & ArkEmail::Internal::Type::request_parameters

      class WebhookRetrieveDeliveryParams < ArkEmail::Internal::Type::BaseModel
        extend ArkEmail::Internal::Type::RequestParameters::Converter
        include ArkEmail::Internal::Type::RequestParameters

        attr_accessor delivery_id: String

        def initialize: (
          delivery_id: String,
          ?request_options: ArkEmail::request_opts
        ) -> void

        def to_hash: -> {
          delivery_id: String,
          request_options: ArkEmail::RequestOptions
        }
      end
    end
  end
end
