module Ark
  module Models
    type dns_record =
      {
        name: String,
        type: Ark::Models::DNSRecord::type_,
        value: String,
        status: Ark::Models::DNSRecord::status?
      }

    class DNSRecord < Ark::Internal::Type::BaseModel
      attr_accessor name: String

      attr_accessor type: Ark::Models::DNSRecord::type_

      attr_accessor value: String

      attr_accessor status: Ark::Models::DNSRecord::status?

      def initialize: (
        name: String,
        type: Ark::Models::DNSRecord::type_,
        value: String,
        ?status: Ark::Models::DNSRecord::status?
      ) -> void

      def to_hash: -> {
        name: String,
        type: Ark::Models::DNSRecord::type_,
        value: String,
        status: Ark::Models::DNSRecord::status?
      }

      type type_ = :TXT | :CNAME | :MX

      module Type
        extend Ark::Internal::Type::Enum

        TXT: :TXT
        CNAME: :CNAME
        MX: :MX

        def self?.values: -> ::Array[Ark::Models::DNSRecord::type_]
      end

      type status = :OK | :Missing | :Invalid

      module Status
        extend Ark::Internal::Type::Enum

        OK: :OK
        MISSING: :Missing
        INVALID: :Invalid

        def self?.values: -> ::Array[Ark::Models::DNSRecord::status]
      end
    end
  end
end
