module Ark
  module Models
    type domain_delete_params = {  } & Ark::Internal::Type::request_parameters

    class DomainDeleteParams < Ark::Internal::Type::BaseModel
      extend Ark::Internal::Type::RequestParameters::Converter
      include Ark::Internal::Type::RequestParameters

      def initialize: (?request_options: Ark::request_opts) -> void

      def to_hash: -> { request_options: Ark::RequestOptions }
    end
  end
end
