module Ark
  module Models
    type domain_create_params =
      { name: String } & Ark::Internal::Type::request_parameters

    class DomainCreateParams < Ark::Internal::Type::BaseModel
      extend Ark::Internal::Type::RequestParameters::Converter
      include Ark::Internal::Type::RequestParameters

      attr_accessor name: String

      def initialize: (
        name: String,
        ?request_options: Ark::request_opts
      ) -> void

      def to_hash: -> { name: String, request_options: Ark::RequestOptions }
    end
  end
end
