module Ark
  module Models
    type email_send_raw_response =
      {
        data: Ark::Models::EmailSendRawResponse::Data,
        meta: Ark::APIMeta,
        success: Ark::Models::EmailSendRawResponse::success
      }

    class EmailSendRawResponse < Ark::Internal::Type::BaseModel
      attr_accessor data: Ark::Models::EmailSendRawResponse::Data

      attr_accessor meta: Ark::APIMeta

      attr_accessor success: Ark::Models::EmailSendRawResponse::success

      def initialize: (
        data: Ark::Models::EmailSendRawResponse::Data,
        meta: Ark::APIMeta,
        success: Ark::Models::EmailSendRawResponse::success
      ) -> void

      def to_hash: -> {
        data: Ark::Models::EmailSendRawResponse::Data,
        meta: Ark::APIMeta,
        success: Ark::Models::EmailSendRawResponse::success
      }

      type data =
        {
          id: String,
          status: Ark::Models::EmailSendRawResponse::Data::status,
          to: ::Array[String],
          message_id: String
        }

      class Data < Ark::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor status: Ark::Models::EmailSendRawResponse::Data::status

        attr_accessor to: ::Array[String]

        attr_reader message_id: String?

        def message_id=: (String) -> String

        def initialize: (
          id: String,
          status: Ark::Models::EmailSendRawResponse::Data::status,
          to: ::Array[String],
          ?message_id: String
        ) -> void

        def to_hash: -> {
          id: String,
          status: Ark::Models::EmailSendRawResponse::Data::status,
          to: ::Array[String],
          message_id: String
        }

        type status = :pending | :sent

        module Status
          extend Ark::Internal::Type::Enum

          PENDING: :pending
          SENT: :sent

          def self?.values: -> ::Array[Ark::Models::EmailSendRawResponse::Data::status]
        end
      end

      type success = true

      module Success
        extend Ark::Internal::Type::Enum

        TRUE: true

        def self?.values: -> ::Array[Ark::Models::EmailSendRawResponse::success]
      end
    end
  end
end
