module Ark
  module Models
    type email_retry_response =
      {
        data: Ark::Models::EmailRetryResponse::Data,
        meta: Ark::APIMeta,
        success: true
      }

    class EmailRetryResponse < Ark::Internal::Type::BaseModel
      attr_accessor data: Ark::Models::EmailRetryResponse::Data

      attr_accessor meta: Ark::APIMeta

      attr_accessor success: true

      def initialize: (
        data: Ark::Models::EmailRetryResponse::Data,
        meta: Ark::APIMeta,
        ?success: true
      ) -> void

      def to_hash: -> {
        data: Ark::Models::EmailRetryResponse::Data,
        meta: Ark::APIMeta,
        success: true
      }

      type data = { message: String }

      class Data < Ark::Internal::Type::BaseModel
        attr_accessor message: String

        def initialize: (message: String) -> void

        def to_hash: -> { message: String }
      end
    end
  end
end
