module Ark
  module Models
    type email_get_deliveries_response =
      {
        data: Ark::Models::EmailGetDeliveriesResponse::Data,
        meta: Ark::APIMeta,
        success: true
      }

    class EmailGetDeliveriesResponse < Ark::Internal::Type::BaseModel
      attr_accessor data: Ark::Models::EmailGetDeliveriesResponse::Data

      attr_accessor meta: Ark::APIMeta

      attr_accessor success: true

      def initialize: (
        data: Ark::Models::EmailGetDeliveriesResponse::Data,
        meta: Ark::APIMeta,
        ?success: true
      ) -> void

      def to_hash: -> {
        data: Ark::Models::EmailGetDeliveriesResponse::Data,
        meta: Ark::APIMeta,
        success: true
      }

      type data =
        {
          deliveries: ::Array[Ark::Delivery],
          message_id: String,
          message_token: String
        }

      class Data < Ark::Internal::Type::BaseModel
        attr_accessor deliveries: ::Array[Ark::Delivery]

        attr_accessor message_id: String

        attr_accessor message_token: String

        def initialize: (
          deliveries: ::Array[Ark::Delivery],
          message_id: String,
          message_token: String
        ) -> void

        def to_hash: -> {
          deliveries: ::Array[Ark::Delivery],
          message_id: String,
          message_token: String
        }
      end
    end
  end
end
