module Ark
  module Models
    type email_retrieve_params =
      { expand: String } & Ark::Internal::Type::request_parameters

    class EmailRetrieveParams < Ark::Internal::Type::BaseModel
      extend Ark::Internal::Type::RequestParameters::Converter
      include Ark::Internal::Type::RequestParameters

      attr_reader expand: String?

      def expand=: (String) -> String

      def initialize: (
        ?expand: String,
        ?request_options: Ark::request_opts
      ) -> void

      def to_hash: -> { expand: String, request_options: Ark::RequestOptions }
    end
  end
end
