module Ark
  module Models
    type email_list_params =
      {
        after: String,
        before: String,
        from: String,
        page: Integer,
        per_page: Integer,
        status: Ark::Models::EmailListParams::status,
        tag: String,
        to: String
      }
      & Ark::Internal::Type::request_parameters

    class EmailListParams < Ark::Internal::Type::BaseModel
      extend Ark::Internal::Type::RequestParameters::Converter
      include Ark::Internal::Type::RequestParameters

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader before: String?

      def before=: (String) -> String

      attr_reader from: String?

      def from=: (String) -> String

      attr_reader page: Integer?

      def page=: (Integer) -> Integer

      attr_reader per_page: Integer?

      def per_page=: (Integer) -> Integer

      attr_reader status: Ark::Models::EmailListParams::status?

      def status=: (
        Ark::Models::EmailListParams::status
      ) -> Ark::Models::EmailListParams::status

      attr_reader tag: String?

      def tag=: (String) -> String

      attr_reader to: String?

      def to=: (String) -> String

      def initialize: (
        ?after: String,
        ?before: String,
        ?from: String,
        ?page: Integer,
        ?per_page: Integer,
        ?status: Ark::Models::EmailListParams::status,
        ?tag: String,
        ?to: String,
        ?request_options: Ark::request_opts
      ) -> void

      def to_hash: -> {
        after: String,
        before: String,
        from: String,
        page: Integer,
        per_page: Integer,
        status: Ark::Models::EmailListParams::status,
        tag: String,
        to: String,
        request_options: Ark::RequestOptions
      }

      type status =
        :queued | :sent | :delivered | :bounced | :failed | :delayed | :held

      module Status
        extend Ark::Internal::Type::Enum

        QUEUED: :queued
        SENT: :sent
        DELIVERED: :delivered
        BOUNCED: :bounced
        FAILED: :failed
        DELAYED: :delayed
        HELD: :held

        def self?.values: -> ::Array[Ark::Models::EmailListParams::status]
      end
    end
  end
end
