module Ark
  module Models
    type success_response =
      {
        data: Ark::SuccessResponse::Data,
        meta: Ark::APIMeta,
        success: Ark::Models::SuccessResponse::success
      }

    class SuccessResponse < Ark::Internal::Type::BaseModel
      attr_accessor data: Ark::SuccessResponse::Data

      attr_accessor meta: Ark::APIMeta

      attr_accessor success: Ark::Models::SuccessResponse::success

      def initialize: (
        data: Ark::SuccessResponse::Data,
        meta: Ark::APIMeta,
        success: Ark::Models::SuccessResponse::success
      ) -> void

      def to_hash: -> {
        data: Ark::SuccessResponse::Data,
        meta: Ark::APIMeta,
        success: Ark::Models::SuccessResponse::success
      }

      type data = { message: String }

      class Data < Ark::Internal::Type::BaseModel
        attr_accessor message: String

        def initialize: (message: String) -> void

        def to_hash: -> { message: String }
      end

      type success = true

      module Success
        extend Ark::Internal::Type::Enum

        TRUE: true

        def self?.values: -> ::Array[Ark::Models::SuccessResponse::success]
      end
    end
  end
end
