module Ark
  module Models
    type suppression_bulk_create_response =
      {
        data: Ark::Models::SuppressionBulkCreateResponse::Data,
        meta: Ark::APIMeta,
        success: true
      }

    class SuppressionBulkCreateResponse < Ark::Internal::Type::BaseModel
      attr_accessor data: Ark::Models::SuppressionBulkCreateResponse::Data

      attr_accessor meta: Ark::APIMeta

      attr_accessor success: true

      def initialize: (
        data: Ark::Models::SuppressionBulkCreateResponse::Data,
        meta: Ark::APIMeta,
        ?success: true
      ) -> void

      def to_hash: -> {
        data: Ark::Models::SuppressionBulkCreateResponse::Data,
        meta: Ark::APIMeta,
        success: true
      }

      type data =
        {
          added: Integer,
          failed: Integer,
          total_requested: Integer,
          updated: Integer
        }

      class Data < Ark::Internal::Type::BaseModel
        attr_accessor added: Integer

        attr_accessor failed: Integer

        attr_accessor total_requested: Integer

        attr_accessor updated: Integer

        def initialize: (
          added: Integer,
          failed: Integer,
          total_requested: Integer,
          updated: Integer
        ) -> void

        def to_hash: -> {
          added: Integer,
          failed: Integer,
          total_requested: Integer,
          updated: Integer
        }
      end
    end
  end
end
