module Ark
  module Models
    type suppression_retrieve_response =
      {
        data: Ark::Models::SuppressionRetrieveResponse::Data,
        meta: Ark::APIMeta,
        success: true
      }

    class SuppressionRetrieveResponse < Ark::Internal::Type::BaseModel
      attr_accessor data: Ark::Models::SuppressionRetrieveResponse::Data

      attr_accessor meta: Ark::APIMeta

      attr_accessor success: true

      def initialize: (
        data: Ark::Models::SuppressionRetrieveResponse::Data,
        meta: Ark::APIMeta,
        ?success: true
      ) -> void

      def to_hash: -> {
        data: Ark::Models::SuppressionRetrieveResponse::Data,
        meta: Ark::APIMeta,
        success: true
      }

      type data =
        {
          address: String,
          suppressed: bool,
          created_at: Time?,
          reason: String?
        }

      class Data < Ark::Internal::Type::BaseModel
        attr_accessor address: String

        attr_accessor suppressed: bool

        attr_accessor created_at: Time?

        attr_accessor reason: String?

        def initialize: (
          address: String,
          suppressed: bool,
          ?created_at: Time?,
          ?reason: String?
        ) -> void

        def to_hash: -> {
          address: String,
          suppressed: bool,
          created_at: Time?,
          reason: String?
        }
      end
    end
  end
end
