module Ark
  module Models
    type suppression_list_response =
      { id: String, address: String, created_at: Time, reason: String }

    class SuppressionListResponse < Ark::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor address: String

      attr_accessor created_at: Time

      attr_reader reason: String?

      def reason=: (String) -> String

      def initialize: (
        id: String,
        address: String,
        created_at: Time,
        ?reason: String
      ) -> void

      def to_hash: -> {
        id: String,
        address: String,
        created_at: Time,
        reason: String
      }
    end
  end
end
