module Ark
  module Models
    type suppression_list_response =
      {
        data: Ark::Models::SuppressionListResponse::Data,
        meta: Ark::APIMeta,
        success: true
      }

    class SuppressionListResponse < Ark::Internal::Type::BaseModel
      attr_accessor data: Ark::Models::SuppressionListResponse::Data

      attr_accessor meta: Ark::APIMeta

      attr_accessor success: true

      def initialize: (
        data: Ark::Models::SuppressionListResponse::Data,
        meta: Ark::APIMeta,
        ?success: true
      ) -> void

      def to_hash: -> {
        data: Ark::Models::SuppressionListResponse::Data,
        meta: Ark::APIMeta,
        success: true
      }

      type data =
        {
          pagination: Ark::Pagination,
          suppressions: ::Array[Ark::Models::SuppressionListResponse::Data::Suppression]
        }

      class Data < Ark::Internal::Type::BaseModel
        attr_accessor pagination: Ark::Pagination

        attr_accessor suppressions: ::Array[Ark::Models::SuppressionListResponse::Data::Suppression]

        def initialize: (
          pagination: Ark::Pagination,
          suppressions: ::Array[Ark::Models::SuppressionListResponse::Data::Suppression]
        ) -> void

        def to_hash: -> {
          pagination: Ark::Pagination,
          suppressions: ::Array[Ark::Models::SuppressionListResponse::Data::Suppression]
        }

        type suppression =
          { id: String, address: String, created_at: Time, reason: String }

        class Suppression < Ark::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor address: String

          attr_accessor created_at: Time

          attr_reader reason: String?

          def reason=: (String) -> String

          def initialize: (
            id: String,
            address: String,
            created_at: Time,
            ?reason: String
          ) -> void

          def to_hash: -> {
            id: String,
            address: String,
            created_at: Time,
            reason: String
          }
        end
      end
    end
  end
end
