module Ark
  module Models
    type tracking_create_params =
      {
        domain_id: String,
        name: String,
        ssl_enabled: bool,
        track_clicks: bool,
        track_opens: bool
      }
      & Ark::Internal::Type::request_parameters

    class TrackingCreateParams < Ark::Internal::Type::BaseModel
      extend Ark::Internal::Type::RequestParameters::Converter
      include Ark::Internal::Type::RequestParameters

      attr_accessor domain_id: String

      attr_accessor name: String

      attr_reader ssl_enabled: bool?

      def ssl_enabled=: (bool) -> bool

      attr_reader track_clicks: bool?

      def track_clicks=: (bool) -> bool

      attr_reader track_opens: bool?

      def track_opens=: (bool) -> bool

      def initialize: (
        domain_id: String,
        name: String,
        ?ssl_enabled: bool,
        ?track_clicks: bool,
        ?track_opens: bool,
        ?request_options: Ark::request_opts
      ) -> void

      def to_hash: -> {
        domain_id: String,
        name: String,
        ssl_enabled: bool,
        track_clicks: bool,
        track_opens: bool,
        request_options: Ark::RequestOptions
      }
    end
  end
end
