module Ark
  module Models
    type track_domain =
      {
        id: String,
        created_at: Time,
        dns_ok: bool,
        domain_id: String,
        full_name: String,
        name: String,
        ssl_enabled: bool,
        track_clicks: bool,
        track_opens: bool,
        dns_checked_at: Time?,
        dns_error: String?,
        dns_record: Ark::TrackDomain::DNSRecord?,
        dns_status: Ark::Models::TrackDomain::dns_status?,
        excluded_click_domains: String?,
        updated_at: Time?
      }

    class TrackDomain < Ark::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor dns_ok: bool

      attr_accessor domain_id: String

      attr_accessor full_name: String

      attr_accessor name: String

      attr_accessor ssl_enabled: bool

      attr_accessor track_clicks: bool

      attr_accessor track_opens: bool

      attr_accessor dns_checked_at: Time?

      attr_accessor dns_error: String?

      attr_accessor dns_record: Ark::TrackDomain::DNSRecord?

      attr_accessor dns_status: Ark::Models::TrackDomain::dns_status?

      attr_accessor excluded_click_domains: String?

      attr_accessor updated_at: Time?

      def initialize: (
        id: String,
        created_at: Time,
        dns_ok: bool,
        domain_id: String,
        full_name: String,
        name: String,
        ssl_enabled: bool,
        track_clicks: bool,
        track_opens: bool,
        ?dns_checked_at: Time?,
        ?dns_error: String?,
        ?dns_record: Ark::TrackDomain::DNSRecord?,
        ?dns_status: Ark::Models::TrackDomain::dns_status?,
        ?excluded_click_domains: String?,
        ?updated_at: Time?
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        dns_ok: bool,
        domain_id: String,
        full_name: String,
        name: String,
        ssl_enabled: bool,
        track_clicks: bool,
        track_opens: bool,
        dns_checked_at: Time?,
        dns_error: String?,
        dns_record: Ark::TrackDomain::DNSRecord?,
        dns_status: Ark::Models::TrackDomain::dns_status?,
        excluded_click_domains: String?,
        updated_at: Time?
      }

      type dns_record = { name: String, type: String, value: String }

      class DNSRecord < Ark::Internal::Type::BaseModel
        attr_reader name: String?

        def name=: (String) -> String

        attr_reader type: String?

        def type=: (String) -> String

        attr_reader value: String?

        def value=: (String) -> String

        def initialize: (?name: String, ?type: String, ?value: String) -> void

        def to_hash: -> { name: String, type: String, value: String }
      end

      type dns_status = :ok | :missing | :invalid

      module DNSStatus
        extend Ark::Internal::Type::Enum

        OK: :ok
        MISSING: :missing
        INVALID: :invalid

        def self?.values: -> ::Array[Ark::Models::TrackDomain::dns_status]
      end
    end
  end
end
