module Ark
  module Models
    type tracking_list_response =
      {
        data: Ark::Models::TrackingListResponse::Data,
        meta: Ark::APIMeta,
        success: Ark::Models::TrackingListResponse::success
      }

    class TrackingListResponse < Ark::Internal::Type::BaseModel
      attr_reader data: Ark::Models::TrackingListResponse::Data?

      def data=: (
        Ark::Models::TrackingListResponse::Data
      ) -> Ark::Models::TrackingListResponse::Data

      attr_reader meta: Ark::APIMeta?

      def meta=: (Ark::APIMeta) -> Ark::APIMeta

      attr_reader success: Ark::Models::TrackingListResponse::success?

      def success=: (
        Ark::Models::TrackingListResponse::success
      ) -> Ark::Models::TrackingListResponse::success

      def initialize: (
        ?data: Ark::Models::TrackingListResponse::Data,
        ?meta: Ark::APIMeta,
        ?success: Ark::Models::TrackingListResponse::success
      ) -> void

      def to_hash: -> {
        data: Ark::Models::TrackingListResponse::Data,
        meta: Ark::APIMeta,
        success: Ark::Models::TrackingListResponse::success
      }

      type data = { track_domains: ::Array[Ark::TrackDomain] }

      class Data < Ark::Internal::Type::BaseModel
        attr_reader track_domains: ::Array[Ark::TrackDomain]?

        def track_domains=: (
          ::Array[Ark::TrackDomain]
        ) -> ::Array[Ark::TrackDomain]

        def initialize: (?track_domains: ::Array[Ark::TrackDomain]) -> void

        def to_hash: -> { track_domains: ::Array[Ark::TrackDomain] }
      end

      type success = true

      module Success
        extend Ark::Internal::Type::Enum

        TRUE: true

        def self?.values: -> ::Array[Ark::Models::TrackingListResponse::success]
      end
    end
  end
end
