# frozen_string_literal: true

# Standard libraries.
# rubocop:disable Lint/RedundantRequireStatement
require "English"
require "base64"
require "cgi"
require "date"
require "erb"
require "etc"
require "json"
require "net/http"
require "openssl"
require "pathname"
require "rbconfig"
require "securerandom"
require "set"
require "stringio"
require "time"
require "uri"
# rubocop:enable Lint/RedundantRequireStatement

# We already ship the preferred sorbet manifests in the package itself.
# `tapioca` currently does not offer us a way to opt out of unnecessary compilation.
if Object.const_defined?(:Tapioca) &&
   caller.chain([$PROGRAM_NAME]).chain(ARGV).any?(/tapioca/) &&
   ARGV.none?(/dsl/)
  return
end

# Gems.
require "connection_pool"

# Package files.
require_relative "ark/version"
require_relative "ark/internal/util"
require_relative "ark/internal/type/converter"
require_relative "ark/internal/type/unknown"
require_relative "ark/internal/type/boolean"
require_relative "ark/internal/type/file_input"
require_relative "ark/internal/type/enum"
require_relative "ark/internal/type/union"
require_relative "ark/internal/type/array_of"
require_relative "ark/internal/type/hash_of"
require_relative "ark/internal/type/base_model"
require_relative "ark/internal/type/base_page"
require_relative "ark/internal/type/request_parameters"
require_relative "ark/internal"
require_relative "ark/request_options"
require_relative "ark/file_part"
require_relative "ark/errors"
require_relative "ark/internal/transport/base_client"
require_relative "ark/internal/transport/pooled_net_requester"
require_relative "ark/client"
require_relative "ark/models/api_meta"
require_relative "ark/models/delivery"
require_relative "ark/models/dns_record"
require_relative "ark/models/domain_create_params"
require_relative "ark/models/domain_delete_params"
require_relative "ark/models/domain_list_params"
require_relative "ark/models/domain_list_response"
require_relative "ark/models/domain_response"
require_relative "ark/models/domain_retrieve_params"
require_relative "ark/models/domain_verify_params"
require_relative "ark/models/email_get_deliveries_params"
require_relative "ark/models/email_get_deliveries_response"
require_relative "ark/models/email_list_params"
require_relative "ark/models/email_list_response"
require_relative "ark/models/email_retrieve_params"
require_relative "ark/models/email_retrieve_response"
require_relative "ark/models/email_retry_params"
require_relative "ark/models/email_retry_response"
require_relative "ark/models/email_send_batch_params"
require_relative "ark/models/email_send_batch_response"
require_relative "ark/models/email_send_params"
require_relative "ark/models/email_send_raw_params"
require_relative "ark/models/pagination"
require_relative "ark/models/send_email"
require_relative "ark/models/success_response"
require_relative "ark/models/suppression_bulk_create_params"
require_relative "ark/models/suppression_bulk_create_response"
require_relative "ark/models/suppression_create_params"
require_relative "ark/models/suppression_create_response"
require_relative "ark/models/suppression_delete_params"
require_relative "ark/models/suppression_list_params"
require_relative "ark/models/suppression_list_response"
require_relative "ark/models/suppression_retrieve_params"
require_relative "ark/models/suppression_retrieve_response"
require_relative "ark/models/track_domain"
require_relative "ark/models/track_domain_response"
require_relative "ark/models/tracking_create_params"
require_relative "ark/models/tracking_delete_params"
require_relative "ark/models/tracking_list_params"
require_relative "ark/models/tracking_list_response"
require_relative "ark/models/tracking_retrieve_params"
require_relative "ark/models/tracking_update_params"
require_relative "ark/models/tracking_verify_params"
require_relative "ark/models/tracking_verify_response"
require_relative "ark/models/webhook_create_params"
require_relative "ark/models/webhook_delete_params"
require_relative "ark/models/webhook_list_params"
require_relative "ark/models/webhook_list_response"
require_relative "ark/models/webhook_response"
require_relative "ark/models/webhook_retrieve_params"
require_relative "ark/models/webhook_test_params"
require_relative "ark/models/webhook_test_response"
require_relative "ark/models/webhook_update_params"
require_relative "ark/models"
require_relative "ark/resources/domains"
require_relative "ark/resources/emails"
require_relative "ark/resources/suppressions"
require_relative "ark/resources/tracking"
require_relative "ark/resources/webhooks"
