# frozen_string_literal: true

# Standard libraries.
# rubocop:disable Lint/RedundantRequireStatement
require "English"
require "base64"
require "cgi"
require "date"
require "erb"
require "etc"
require "json"
require "net/http"
require "openssl"
require "pathname"
require "rbconfig"
require "securerandom"
require "set"
require "stringio"
require "time"
require "uri"
# rubocop:enable Lint/RedundantRequireStatement

# We already ship the preferred sorbet manifests in the package itself.
# `tapioca` currently does not offer us a way to opt out of unnecessary compilation.
if Object.const_defined?(:Tapioca) &&
   caller.chain([$PROGRAM_NAME]).chain(ARGV).any?(/tapioca/) &&
   ARGV.none?(/dsl/)
  return
end

# Gems.
require "connection_pool"

# Package files.
require_relative "ark_email/version"
require_relative "ark_email/internal/util"
require_relative "ark_email/internal/type/converter"
require_relative "ark_email/internal/type/unknown"
require_relative "ark_email/internal/type/boolean"
require_relative "ark_email/internal/type/file_input"
require_relative "ark_email/internal/type/enum"
require_relative "ark_email/internal/type/union"
require_relative "ark_email/internal/type/array_of"
require_relative "ark_email/internal/type/hash_of"
require_relative "ark_email/internal/type/base_model"
require_relative "ark_email/internal/type/base_page"
require_relative "ark_email/internal/type/request_parameters"
require_relative "ark_email/internal"
require_relative "ark_email/request_options"
require_relative "ark_email/file_part"
require_relative "ark_email/errors"
require_relative "ark_email/internal/transport/base_client"
require_relative "ark_email/internal/transport/pooled_net_requester"
require_relative "ark_email/client"
require_relative "ark_email/internal/page_number_pagination"
require_relative "ark_email/models/log_entry"
require_relative "ark_email/models/api_meta"
require_relative "ark_email/models/dns_record"
require_relative "ark_email/models/domain_create_params"
require_relative "ark_email/models/domain_create_response"
require_relative "ark_email/models/domain_delete_params"
require_relative "ark_email/models/domain_delete_response"
require_relative "ark_email/models/domain_list_params"
require_relative "ark_email/models/domain_list_response"
require_relative "ark_email/models/domain_retrieve_params"
require_relative "ark_email/models/domain_retrieve_response"
require_relative "ark_email/models/domain_verify_params"
require_relative "ark_email/models/domain_verify_response"
require_relative "ark_email/models/email_list_params"
require_relative "ark_email/models/email_list_response"
require_relative "ark_email/models/email_retrieve_deliveries_params"
require_relative "ark_email/models/email_retrieve_deliveries_response"
require_relative "ark_email/models/email_retrieve_params"
require_relative "ark_email/models/email_retrieve_response"
require_relative "ark_email/models/email_retry_params"
require_relative "ark_email/models/email_retry_response"
require_relative "ark_email/models/email_send_batch_params"
require_relative "ark_email/models/email_send_batch_response"
require_relative "ark_email/models/email_send_params"
require_relative "ark_email/models/email_send_raw_params"
require_relative "ark_email/models/email_send_raw_response"
require_relative "ark_email/models/email_send_response"
require_relative "ark_email/models/log_entry_detail"
require_relative "ark_email/models/log_list_params"
require_relative "ark_email/models/log_retrieve_params"
require_relative "ark_email/models/log_retrieve_response"
require_relative "ark_email/models/suppression_bulk_create_params"
require_relative "ark_email/models/suppression_bulk_create_response"
require_relative "ark_email/models/suppression_create_params"
require_relative "ark_email/models/suppression_create_response"
require_relative "ark_email/models/suppression_delete_params"
require_relative "ark_email/models/suppression_delete_response"
require_relative "ark_email/models/suppression_list_params"
require_relative "ark_email/models/suppression_list_response"
require_relative "ark_email/models/suppression_retrieve_params"
require_relative "ark_email/models/suppression_retrieve_response"
require_relative "ark_email/models/tenant"
require_relative "ark_email/models/tenant_create_params"
require_relative "ark_email/models/tenant_create_response"
require_relative "ark_email/models/tenant_delete_params"
require_relative "ark_email/models/tenant_delete_response"
require_relative "ark_email/models/tenant_list_params"
require_relative "ark_email/models/tenant_retrieve_params"
require_relative "ark_email/models/tenant_retrieve_response"
require_relative "ark_email/models/tenant_update_params"
require_relative "ark_email/models/tenant_update_response"
require_relative "ark_email/models/track_domain"
require_relative "ark_email/models/tracking_create_params"
require_relative "ark_email/models/tracking_create_response"
require_relative "ark_email/models/tracking_delete_params"
require_relative "ark_email/models/tracking_delete_response"
require_relative "ark_email/models/tracking_list_params"
require_relative "ark_email/models/tracking_list_response"
require_relative "ark_email/models/tracking_retrieve_params"
require_relative "ark_email/models/tracking_retrieve_response"
require_relative "ark_email/models/tracking_update_params"
require_relative "ark_email/models/tracking_update_response"
require_relative "ark_email/models/tracking_verify_params"
require_relative "ark_email/models/tracking_verify_response"
require_relative "ark_email/models/usage_retrieve_params"
require_relative "ark_email/models/usage_retrieve_response"
require_relative "ark_email/models/webhook_create_params"
require_relative "ark_email/models/webhook_create_response"
require_relative "ark_email/models/webhook_delete_params"
require_relative "ark_email/models/webhook_delete_response"
require_relative "ark_email/models/webhook_list_deliveries_params"
require_relative "ark_email/models/webhook_list_deliveries_response"
require_relative "ark_email/models/webhook_list_params"
require_relative "ark_email/models/webhook_list_response"
require_relative "ark_email/models/webhook_replay_delivery_params"
require_relative "ark_email/models/webhook_replay_delivery_response"
require_relative "ark_email/models/webhook_retrieve_delivery_params"
require_relative "ark_email/models/webhook_retrieve_delivery_response"
require_relative "ark_email/models/webhook_retrieve_params"
require_relative "ark_email/models/webhook_retrieve_response"
require_relative "ark_email/models/webhook_test_params"
require_relative "ark_email/models/webhook_test_response"
require_relative "ark_email/models/webhook_update_params"
require_relative "ark_email/models/webhook_update_response"
require_relative "ark_email/models"
require_relative "ark_email/resources/domains"
require_relative "ark_email/resources/emails"
require_relative "ark_email/resources/logs"
require_relative "ark_email/resources/suppressions"
require_relative "ark_email/resources/tenants"
require_relative "ark_email/resources/tracking"
require_relative "ark_email/resources/usage"
require_relative "ark_email/resources/webhooks"
