module ArkEmail
  class Client < ArkEmail::Internal::Transport::BaseClient
    DEFAULT_MAX_RETRIES: 2

    DEFAULT_TIMEOUT_IN_SECONDS: Float

    DEFAULT_INITIAL_RETRY_DELAY: Float

    DEFAULT_MAX_RETRY_DELAY: Float

    attr_reader api_key: String

    attr_reader emails: ArkEmail::Resources::Emails

    attr_reader domains: ArkEmail::Resources::Domains

    attr_reader suppressions: ArkEmail::Resources::Suppressions

    attr_reader webhooks: ArkEmail::Resources::Webhooks

    attr_reader tracking: ArkEmail::Resources::Tracking

    attr_reader logs: ArkEmail::Resources::Logs

    attr_reader usage: ArkEmail::Resources::Usage

    attr_reader tenants: ArkEmail::Resources::Tenants

    private def auth_headers: -> ::Hash[String, String]

    def initialize: (
      ?api_key: String?,
      ?base_url: String?,
      ?max_retries: Integer,
      ?timeout: Float,
      ?initial_retry_delay: Float,
      ?max_retry_delay: Float
    ) -> void
  end
end
