module ArkEmail
  class APIMeta = ArkEmail::Models::APIMeta

  class EmailCounts = ArkEmail::Models::EmailCounts

  class EmailListParams = ArkEmail::Models::EmailListParams

  class EmailRates = ArkEmail::Models::EmailRates

  class EmailRetrieveDeliveriesParams = ArkEmail::Models::EmailRetrieveDeliveriesParams

  class EmailRetrieveParams = ArkEmail::Models::EmailRetrieveParams

  class EmailRetryParams = ArkEmail::Models::EmailRetryParams

  class EmailSendBatchParams = ArkEmail::Models::EmailSendBatchParams

  class EmailSendParams = ArkEmail::Models::EmailSendParams

  class EmailSendRawParams = ArkEmail::Models::EmailSendRawParams

  class LimitRetrieveParams = ArkEmail::Models::LimitRetrieveParams

  class LimitsData = ArkEmail::Models::LimitsData

  class LogEntry = ArkEmail::Models::LogEntry

  class LogEntryDetail = ArkEmail::Models::LogEntryDetail

  class LogListParams = ArkEmail::Models::LogListParams

  class LogRetrieveParams = ArkEmail::Models::LogRetrieveParams

  class OrgUsageSummary = ArkEmail::Models::OrgUsageSummary

  module Platform = ArkEmail::Models::Platform

  class Tenant = ArkEmail::Models::Tenant

  class TenantCreateParams = ArkEmail::Models::TenantCreateParams

  class TenantDeleteParams = ArkEmail::Models::TenantDeleteParams

  class TenantListParams = ArkEmail::Models::TenantListParams

  class TenantRetrieveParams = ArkEmail::Models::TenantRetrieveParams

  module Tenants = ArkEmail::Models::Tenants

  class TenantUpdateParams = ArkEmail::Models::TenantUpdateParams

  class TenantUsageItem = ArkEmail::Models::TenantUsageItem

  class UsageExportParams = ArkEmail::Models::UsageExportParams

  class UsageListTenantsParams = ArkEmail::Models::UsageListTenantsParams

  class UsagePeriod = ArkEmail::Models::UsagePeriod

  class UsageRetrieveParams = ArkEmail::Models::UsageRetrieveParams
end
