module Ark
  class APIMeta = Ark::Models::APIMeta

  class DNSRecord = Ark::Models::DNSRecord

  class DomainCreateParams = Ark::Models::DomainCreateParams

  class DomainDeleteParams = Ark::Models::DomainDeleteParams

  class DomainListParams = Ark::Models::DomainListParams

  class DomainRetrieveParams = Ark::Models::DomainRetrieveParams

  class DomainVerifyParams = Ark::Models::DomainVerifyParams

  class EmailListParams = Ark::Models::EmailListParams

  class EmailRetrieveDeliveriesParams = Ark::Models::EmailRetrieveDeliveriesParams

  class EmailRetrieveParams = Ark::Models::EmailRetrieveParams

  class EmailRetryParams = Ark::Models::EmailRetryParams

  class EmailSendBatchParams = Ark::Models::EmailSendBatchParams

  class EmailSendParams = Ark::Models::EmailSendParams

  class EmailSendRawParams = Ark::Models::EmailSendRawParams

  class SuppressionBulkCreateParams = Ark::Models::SuppressionBulkCreateParams

  class SuppressionCreateParams = Ark::Models::SuppressionCreateParams

  class SuppressionDeleteParams = Ark::Models::SuppressionDeleteParams

  class SuppressionListParams = Ark::Models::SuppressionListParams

  class SuppressionRetrieveParams = Ark::Models::SuppressionRetrieveParams

  class TrackDomain = Ark::Models::TrackDomain

  class TrackingCreateParams = Ark::Models::TrackingCreateParams

  class TrackingDeleteParams = Ark::Models::TrackingDeleteParams

  class TrackingListParams = Ark::Models::TrackingListParams

  class TrackingRetrieveParams = Ark::Models::TrackingRetrieveParams

  class TrackingUpdateParams = Ark::Models::TrackingUpdateParams

  class TrackingVerifyParams = Ark::Models::TrackingVerifyParams

  class WebhookCreateParams = Ark::Models::WebhookCreateParams

  class WebhookDeleteParams = Ark::Models::WebhookDeleteParams

  class WebhookListParams = Ark::Models::WebhookListParams

  class WebhookRetrieveParams = Ark::Models::WebhookRetrieveParams

  class WebhookTestParams = Ark::Models::WebhookTestParams

  class WebhookUpdateParams = Ark::Models::WebhookUpdateParams
end
