module ArkEmail
  module Resources
    class Domains
      def create: (
        name: String,
        ?request_options: ArkEmail::request_opts
      ) -> ArkEmail::Models::DomainCreateResponse

      def retrieve: (
        String domain_id,
        ?request_options: ArkEmail::request_opts
      ) -> ArkEmail::Models::DomainRetrieveResponse

      def list: (
        ?request_options: ArkEmail::request_opts
      ) -> ArkEmail::Models::DomainListResponse

      def delete: (
        String domain_id,
        ?request_options: ArkEmail::request_opts
      ) -> ArkEmail::Models::DomainDeleteResponse

      def verify: (
        String domain_id,
        ?request_options: ArkEmail::request_opts
      ) -> ArkEmail::Models::DomainVerifyResponse

      def initialize: (client: ArkEmail::Client) -> void
    end
  end
end
