module ArkEmail
  module Resources
    class Emails
      def retrieve: (
        String email_id,
        ?expand: String,
        ?request_options: ArkEmail::request_opts
      ) -> ArkEmail::Models::EmailRetrieveResponse

      def list: (
        ?after: String,
        ?before: String,
        ?from: String,
        ?page: Integer,
        ?per_page: Integer,
        ?status: ArkEmail::Models::EmailListParams::status,
        ?tag: String,
        ?to: String,
        ?request_options: ArkEmail::request_opts
      ) -> ArkEmail::Internal::PageNumberPagination[ArkEmail::Models::EmailListResponse]

      def retrieve_deliveries: (
        String email_id,
        ?request_options: ArkEmail::request_opts
      ) -> ArkEmail::Models::EmailRetrieveDeliveriesResponse

      def retry_: (
        String email_id,
        ?request_options: ArkEmail::request_opts
      ) -> ArkEmail::Models::EmailRetryResponse

      def send_: (
        from: String,
        subject: String,
        to: ::Array[String],
        ?attachments: ::Array[ArkEmail::EmailSendParams::Attachment]?,
        ?bcc: ::Array[String]?,
        ?cc: ::Array[String]?,
        ?headers: ::Hash[Symbol, String]?,
        ?html: String?,
        ?metadata: ::Hash[Symbol, String]?,
        ?reply_to: String?,
        ?tag: String?,
        ?text: String?,
        ?idempotency_key: String,
        ?request_options: ArkEmail::request_opts
      ) -> ArkEmail::Models::EmailSendResponse

      def send_batch: (
        emails: ::Array[ArkEmail::EmailSendBatchParams::Email],
        from: String,
        ?idempotency_key: String,
        ?request_options: ArkEmail::request_opts
      ) -> ArkEmail::Models::EmailSendBatchResponse

      def send_raw: (
        data: String,
        mail_from: String,
        rcpt_to: ::Array[String],
        ?bounce: bool?,
        ?request_options: ArkEmail::request_opts
      ) -> ArkEmail::Models::EmailSendRawResponse

      def initialize: (client: ArkEmail::Client) -> void
    end
  end
end
