module ArkEmail
  module Resources
    class Tracking
      def create: (
        domain_id: Integer,
        name: String,
        ?ssl_enabled: bool?,
        ?track_clicks: bool?,
        ?track_opens: bool?,
        ?request_options: ArkEmail::request_opts
      ) -> ArkEmail::Models::TrackingCreateResponse

      def retrieve: (
        String tracking_id,
        ?request_options: ArkEmail::request_opts
      ) -> ArkEmail::Models::TrackingRetrieveResponse

      def update: (
        String tracking_id,
        ?excluded_click_domains: String?,
        ?ssl_enabled: bool?,
        ?track_clicks: bool?,
        ?track_opens: bool?,
        ?request_options: ArkEmail::request_opts
      ) -> ArkEmail::Models::TrackingUpdateResponse

      def list: (
        ?request_options: ArkEmail::request_opts
      ) -> ArkEmail::Models::TrackingListResponse

      def delete: (
        String tracking_id,
        ?request_options: ArkEmail::request_opts
      ) -> ArkEmail::Models::TrackingDeleteResponse

      def verify: (
        String tracking_id,
        ?request_options: ArkEmail::request_opts
      ) -> ArkEmail::Models::TrackingVerifyResponse

      def initialize: (client: ArkEmail::Client) -> void
    end
  end
end
