module ArkEmail
  module Resources
    class Usage
      def retrieve: (
        ?period: String,
        ?timezone: String,
        ?request_options: ArkEmail::request_opts
      ) -> ArkEmail::OrgUsageSummary

      def export: (
        ?format_: ArkEmail::Models::UsageExportParams::format_,
        ?min_sent: Integer,
        ?period: String,
        ?status: ArkEmail::Models::UsageExportParams::status,
        ?timezone: String,
        ?request_options: ArkEmail::request_opts
      ) -> ArkEmail::Models::usage_export_response

      def list_tenants: (
        ?min_sent: Integer,
        ?page: Integer,
        ?period: String,
        ?per_page: Integer,
        ?sort: ArkEmail::Models::UsageListTenantsParams::sort,
        ?status: ArkEmail::Models::UsageListTenantsParams::status,
        ?timezone: String,
        ?request_options: ArkEmail::request_opts
      ) -> ArkEmail::Internal::PageNumberPagination[ArkEmail::TenantUsageItem]

      def initialize: (client: ArkEmail::Client) -> void
    end
  end
end
