module ArkEmail
  module Resources
    class Webhooks
      def create: (
        name: String,
        url: String,
        ?all_events: bool?,
        ?enabled: bool?,
        ?events: ::Array[ArkEmail::Models::WebhookCreateParams::event]?,
        ?request_options: ArkEmail::request_opts
      ) -> ArkEmail::Models::WebhookCreateResponse

      def retrieve: (
        String webhook_id,
        ?request_options: ArkEmail::request_opts
      ) -> ArkEmail::Models::WebhookRetrieveResponse

      def update: (
        String webhook_id,
        ?all_events: bool?,
        ?enabled: bool?,
        ?events: ::Array[String]?,
        ?name: String?,
        ?url: String?,
        ?request_options: ArkEmail::request_opts
      ) -> ArkEmail::Models::WebhookUpdateResponse

      def list: (
        ?request_options: ArkEmail::request_opts
      ) -> ArkEmail::Models::WebhookListResponse

      def delete: (
        String webhook_id,
        ?request_options: ArkEmail::request_opts
      ) -> ArkEmail::Models::WebhookDeleteResponse

      def list_deliveries: (
        String webhook_id,
        ?after: Integer,
        ?before: Integer,
        ?event: ArkEmail::Models::WebhookListDeliveriesParams::event,
        ?page: Integer,
        ?per_page: Integer,
        ?success: bool,
        ?request_options: ArkEmail::request_opts
      ) -> ArkEmail::Models::WebhookListDeliveriesResponse

      def replay_delivery: (
        String delivery_id,
        webhook_id: String,
        ?request_options: ArkEmail::request_opts
      ) -> ArkEmail::Models::WebhookReplayDeliveryResponse

      def retrieve_delivery: (
        String delivery_id,
        webhook_id: String,
        ?request_options: ArkEmail::request_opts
      ) -> ArkEmail::Models::WebhookRetrieveDeliveryResponse

      def test_: (
        String webhook_id,
        event: ArkEmail::Models::WebhookTestParams::event,
        ?request_options: ArkEmail::request_opts
      ) -> ArkEmail::Models::WebhookTestResponse

      def initialize: (client: ArkEmail::Client) -> void
    end
  end
end
