module ArkEmail
  module Models
    type domain_retrieve_response =
      {
        data: ArkEmail::Models::DomainRetrieveResponse::Data,
        meta: ArkEmail::APIMeta,
        success: true
      }

    class DomainRetrieveResponse < ArkEmail::Internal::Type::BaseModel
      attr_accessor data: ArkEmail::Models::DomainRetrieveResponse::Data

      attr_accessor meta: ArkEmail::APIMeta

      attr_accessor success: true

      def initialize: (
        data: ArkEmail::Models::DomainRetrieveResponse::Data,
        meta: ArkEmail::APIMeta,
        ?success: true
      ) -> void

      def to_hash: -> {
        data: ArkEmail::Models::DomainRetrieveResponse::Data,
        meta: ArkEmail::APIMeta,
        success: true
      }

      type data =
        {
          id: Integer,
          created_at: Time,
          dns_records: ArkEmail::Models::DomainRetrieveResponse::Data::DNSRecords?,
          name: String,
          uuid: String,
          verified: bool,
          verified_at: Time?
        }

      class Data < ArkEmail::Internal::Type::BaseModel
        attr_accessor id: Integer

        attr_accessor created_at: Time

        attr_accessor dns_records: ArkEmail::Models::DomainRetrieveResponse::Data::DNSRecords?

        attr_accessor name: String

        attr_accessor uuid: String

        attr_accessor verified: bool

        attr_accessor verified_at: Time?

        def initialize: (
          id: Integer,
          created_at: Time,
          dns_records: ArkEmail::Models::DomainRetrieveResponse::Data::DNSRecords?,
          name: String,
          uuid: String,
          verified: bool,
          ?verified_at: Time?
        ) -> void

        def to_hash: -> {
          id: Integer,
          created_at: Time,
          dns_records: ArkEmail::Models::DomainRetrieveResponse::Data::DNSRecords?,
          name: String,
          uuid: String,
          verified: bool,
          verified_at: Time?
        }

        type dns_records =
          {
            dkim: ArkEmail::DNSRecord?,
            return_path: ArkEmail::DNSRecord?,
            spf: ArkEmail::DNSRecord?,
            zone: String
          }

        class DNSRecords < ArkEmail::Internal::Type::BaseModel
          attr_accessor dkim: ArkEmail::DNSRecord?

          attr_accessor return_path: ArkEmail::DNSRecord?

          attr_accessor spf: ArkEmail::DNSRecord?

          attr_reader zone: String?

          def zone=: (String) -> String

          def initialize: (
            ?dkim: ArkEmail::DNSRecord?,
            ?return_path: ArkEmail::DNSRecord?,
            ?spf: ArkEmail::DNSRecord?,
            ?zone: String
          ) -> void

          def to_hash: -> {
            dkim: ArkEmail::DNSRecord?,
            return_path: ArkEmail::DNSRecord?,
            spf: ArkEmail::DNSRecord?,
            zone: String
          }
        end
      end
    end
  end
end
