module ArkEmail
  module Models
    type email_counts =
      {
        bounced: Integer,
        delivered: Integer,
        hard_failed: Integer,
        held: Integer,
        sent: Integer,
        soft_failed: Integer
      }

    class EmailCounts < ArkEmail::Internal::Type::BaseModel
      attr_accessor bounced: Integer

      attr_accessor delivered: Integer

      attr_accessor hard_failed: Integer

      attr_accessor held: Integer

      attr_accessor sent: Integer

      attr_accessor soft_failed: Integer

      def initialize: (
        bounced: Integer,
        delivered: Integer,
        hard_failed: Integer,
        held: Integer,
        sent: Integer,
        soft_failed: Integer
      ) -> void

      def to_hash: -> {
        bounced: Integer,
        delivered: Integer,
        hard_failed: Integer,
        held: Integer,
        sent: Integer,
        soft_failed: Integer
      }
    end
  end
end
