module ArkEmail
  module Models
    type email_send_raw_params =
      {
        from: String,
        raw_message: String,
        to: ::Array[String],
        bounce: bool?,
        tenant_id: String?
      }
      & ArkEmail::Internal::Type::request_parameters

    class EmailSendRawParams < ArkEmail::Internal::Type::BaseModel
      extend ArkEmail::Internal::Type::RequestParameters::Converter
      include ArkEmail::Internal::Type::RequestParameters

      attr_accessor from: String

      attr_accessor raw_message: String

      attr_accessor to: ::Array[String]

      attr_accessor bounce: bool?

      attr_accessor tenant_id: String?

      def initialize: (
        from: String,
        raw_message: String,
        to: ::Array[String],
        ?bounce: bool?,
        ?tenant_id: String?,
        ?request_options: ArkEmail::request_opts
      ) -> void

      def to_hash: -> {
        from: String,
        raw_message: String,
        to: ::Array[String],
        bounce: bool?,
        tenant_id: String?,
        request_options: ArkEmail::RequestOptions
      }
    end
  end
end
