module ArkEmail
  module Models
    type email_retry_response =
      {
        data: ArkEmail::Models::EmailRetryResponse::Data,
        meta: ArkEmail::APIMeta,
        success: true
      }

    class EmailRetryResponse < ArkEmail::Internal::Type::BaseModel
      attr_accessor data: ArkEmail::Models::EmailRetryResponse::Data

      attr_accessor meta: ArkEmail::APIMeta

      attr_accessor success: true

      def initialize: (
        data: ArkEmail::Models::EmailRetryResponse::Data,
        meta: ArkEmail::APIMeta,
        ?success: true
      ) -> void

      def to_hash: -> {
        data: ArkEmail::Models::EmailRetryResponse::Data,
        meta: ArkEmail::APIMeta,
        success: true
      }

      type data = { id: String, message: String }

      class Data < ArkEmail::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor message: String

        def initialize: (id: String, message: String) -> void

        def to_hash: -> { id: String, message: String }
      end
    end
  end
end
