module ArkEmail
  module Models
    type email_send_batch_response =
      {
        data: ArkEmail::Models::EmailSendBatchResponse::Data,
        meta: ArkEmail::APIMeta,
        success: true
      }

    class EmailSendBatchResponse < ArkEmail::Internal::Type::BaseModel
      attr_accessor data: ArkEmail::Models::EmailSendBatchResponse::Data

      attr_accessor meta: ArkEmail::APIMeta

      attr_accessor success: true

      def initialize: (
        data: ArkEmail::Models::EmailSendBatchResponse::Data,
        meta: ArkEmail::APIMeta,
        ?success: true
      ) -> void

      def to_hash: -> {
        data: ArkEmail::Models::EmailSendBatchResponse::Data,
        meta: ArkEmail::APIMeta,
        success: true
      }

      type data =
        {
          accepted: Integer,
          failed: Integer,
          messages: ::Hash[Symbol, ArkEmail::Models::EmailSendBatchResponse::Data::Message],
          tenant_id: String,
          total: Integer,
          sandbox: bool
        }

      class Data < ArkEmail::Internal::Type::BaseModel
        attr_accessor accepted: Integer

        attr_accessor failed: Integer

        attr_accessor messages: ::Hash[Symbol, ArkEmail::Models::EmailSendBatchResponse::Data::Message]

        attr_accessor tenant_id: String

        attr_accessor total: Integer

        attr_reader sandbox: bool?

        def sandbox=: (bool) -> bool

        def initialize: (
          accepted: Integer,
          failed: Integer,
          messages: ::Hash[Symbol, ArkEmail::Models::EmailSendBatchResponse::Data::Message],
          tenant_id: String,
          total: Integer,
          ?sandbox: bool
        ) -> void

        def to_hash: -> {
          accepted: Integer,
          failed: Integer,
          messages: ::Hash[Symbol, ArkEmail::Models::EmailSendBatchResponse::Data::Message],
          tenant_id: String,
          total: Integer,
          sandbox: bool
        }

        type message = { id: String }

        class Message < ArkEmail::Internal::Type::BaseModel
          attr_accessor id: String

          def initialize: (id: String) -> void

          def to_hash: -> { id: String }
        end
      end
    end
  end
end
