module ArkEmail
  module Models
    type log_entry =
      {
        context: ArkEmail::LogEntry::Context,
        credential: ArkEmail::LogEntry::Credential,
        duration_ms: Integer,
        endpoint: String,
        method_: ArkEmail::Models::LogEntry::method_,
        path: String,
        rate_limit: ArkEmail::LogEntry::RateLimit,
        request_id: String,
        status_code: Integer,
        timestamp: Time,
        email: ArkEmail::LogEntry::Email?,
        error: ArkEmail::LogEntry::Error?,
        sdk: ArkEmail::LogEntry::SDK?
      }

    class LogEntry < ArkEmail::Internal::Type::BaseModel
      attr_accessor context: ArkEmail::LogEntry::Context

      attr_accessor credential: ArkEmail::LogEntry::Credential

      attr_accessor duration_ms: Integer

      attr_accessor endpoint: String

      attr_accessor method_: ArkEmail::Models::LogEntry::method_

      attr_accessor path: String

      attr_accessor rate_limit: ArkEmail::LogEntry::RateLimit

      attr_accessor request_id: String

      attr_accessor status_code: Integer

      attr_accessor timestamp: Time

      attr_accessor email: ArkEmail::LogEntry::Email?

      attr_accessor error: ArkEmail::LogEntry::Error?

      attr_accessor sdk: ArkEmail::LogEntry::SDK?

      def initialize: (
        context: ArkEmail::LogEntry::Context,
        credential: ArkEmail::LogEntry::Credential,
        duration_ms: Integer,
        endpoint: String,
        method_: ArkEmail::Models::LogEntry::method_,
        path: String,
        rate_limit: ArkEmail::LogEntry::RateLimit,
        request_id: String,
        status_code: Integer,
        timestamp: Time,
        ?email: ArkEmail::LogEntry::Email?,
        ?error: ArkEmail::LogEntry::Error?,
        ?sdk: ArkEmail::LogEntry::SDK?
      ) -> void

      def to_hash: -> {
        context: ArkEmail::LogEntry::Context,
        credential: ArkEmail::LogEntry::Credential,
        duration_ms: Integer,
        endpoint: String,
        method_: ArkEmail::Models::LogEntry::method_,
        path: String,
        rate_limit: ArkEmail::LogEntry::RateLimit,
        request_id: String,
        status_code: Integer,
        timestamp: Time,
        email: ArkEmail::LogEntry::Email?,
        error: ArkEmail::LogEntry::Error?,
        sdk: ArkEmail::LogEntry::SDK?
      }

      type context =
        {
          idempotency_key: String?,
          ip_address: String?,
          query_params: ::Hash[Symbol, top]?,
          user_agent: String?
        }

      class Context < ArkEmail::Internal::Type::BaseModel
        attr_accessor idempotency_key: String?

        attr_accessor ip_address: String?

        attr_accessor query_params: ::Hash[Symbol, top]?

        attr_accessor user_agent: String?

        def initialize: (
          ?idempotency_key: String?,
          ?ip_address: String?,
          ?query_params: ::Hash[Symbol, top]?,
          ?user_agent: String?
        ) -> void

        def to_hash: -> {
          idempotency_key: String?,
          ip_address: String?,
          query_params: ::Hash[Symbol, top]?,
          user_agent: String?
        }
      end

      type credential = { id: String, key_prefix: String? }

      class Credential < ArkEmail::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor key_prefix: String?

        def initialize: (id: String, ?key_prefix: String?) -> void

        def to_hash: -> { id: String, key_prefix: String? }
      end

      type method_ = :GET | :POST | :PUT | :PATCH | :DELETE

      module Method
        extend ArkEmail::Internal::Type::Enum

        GET: :GET
        POST: :POST
        PUT: :PUT
        PATCH: :PATCH
        DELETE: :DELETE

        def self?.values: -> ::Array[ArkEmail::Models::LogEntry::method_]
      end

      type rate_limit =
        { limit: Integer?, limited: bool, remaining: Integer?, reset: Integer? }

      class RateLimit < ArkEmail::Internal::Type::BaseModel
        attr_accessor limit: Integer?

        attr_reader limited: bool?

        def limited=: (bool) -> bool

        attr_accessor remaining: Integer?

        attr_accessor reset: Integer?

        def initialize: (
          ?limit: Integer?,
          ?limited: bool,
          ?remaining: Integer?,
          ?reset: Integer?
        ) -> void

        def to_hash: -> {
          limit: Integer?,
          limited: bool,
          remaining: Integer?,
          reset: Integer?
        }
      end

      type email = { id: String, recipient_count: Integer? }

      class Email < ArkEmail::Internal::Type::BaseModel
        attr_reader id: String?

        def id=: (String) -> String

        attr_accessor recipient_count: Integer?

        def initialize: (?id: String, ?recipient_count: Integer?) -> void

        def to_hash: -> { id: String, recipient_count: Integer? }
      end

      type error = { code: String, message: String? }

      class Error < ArkEmail::Internal::Type::BaseModel
        attr_reader code: String?

        def code=: (String) -> String

        attr_accessor message: String?

        def initialize: (?code: String, ?message: String?) -> void

        def to_hash: -> { code: String, message: String? }
      end

      type sdk = { name: String, version: String? }

      class SDK < ArkEmail::Internal::Type::BaseModel
        attr_reader name: String?

        def name=: (String) -> String

        attr_accessor version: String?

        def initialize: (?name: String, ?version: String?) -> void

        def to_hash: -> { name: String, version: String? }
      end
    end
  end
end
