module ArkEmail
  module Models
    type suppression_bulk_create_params =
      {
        suppressions: ::Array[ArkEmail::SuppressionBulkCreateParams::Suppression]
      }
      & ArkEmail::Internal::Type::request_parameters

    class SuppressionBulkCreateParams < ArkEmail::Internal::Type::BaseModel
      extend ArkEmail::Internal::Type::RequestParameters::Converter
      include ArkEmail::Internal::Type::RequestParameters

      attr_accessor suppressions: ::Array[ArkEmail::SuppressionBulkCreateParams::Suppression]

      def initialize: (
        suppressions: ::Array[ArkEmail::SuppressionBulkCreateParams::Suppression],
        ?request_options: ArkEmail::request_opts
      ) -> void

      def to_hash: -> {
        suppressions: ::Array[ArkEmail::SuppressionBulkCreateParams::Suppression],
        request_options: ArkEmail::RequestOptions
      }

      type suppression = { address: String, reason: String? }

      class Suppression < ArkEmail::Internal::Type::BaseModel
        attr_accessor address: String

        attr_accessor reason: String?

        def initialize: (address: String, ?reason: String?) -> void

        def to_hash: -> { address: String, reason: String? }
      end
    end
  end
end
