module ArkEmail
  module Models
    type tracking_update_params =
      {
        excluded_click_domains: String?,
        ssl_enabled: bool?,
        track_clicks: bool?,
        track_opens: bool?
      }
      & ArkEmail::Internal::Type::request_parameters

    class TrackingUpdateParams < ArkEmail::Internal::Type::BaseModel
      extend ArkEmail::Internal::Type::RequestParameters::Converter
      include ArkEmail::Internal::Type::RequestParameters

      attr_accessor excluded_click_domains: String?

      attr_accessor ssl_enabled: bool?

      attr_accessor track_clicks: bool?

      attr_accessor track_opens: bool?

      def initialize: (
        ?excluded_click_domains: String?,
        ?ssl_enabled: bool?,
        ?track_clicks: bool?,
        ?track_opens: bool?,
        ?request_options: ArkEmail::request_opts
      ) -> void

      def to_hash: -> {
        excluded_click_domains: String?,
        ssl_enabled: bool?,
        track_clicks: bool?,
        track_opens: bool?,
        request_options: ArkEmail::RequestOptions
      }
    end
  end
end
