module ArkEmail
  module Models
    type tracking_list_response =
      {
        data: ArkEmail::Models::TrackingListResponse::Data,
        meta: ArkEmail::APIMeta,
        success: true
      }

    class TrackingListResponse < ArkEmail::Internal::Type::BaseModel
      attr_accessor data: ArkEmail::Models::TrackingListResponse::Data

      attr_accessor meta: ArkEmail::APIMeta

      attr_accessor success: true

      def initialize: (
        data: ArkEmail::Models::TrackingListResponse::Data,
        meta: ArkEmail::APIMeta,
        ?success: true
      ) -> void

      def to_hash: -> {
        data: ArkEmail::Models::TrackingListResponse::Data,
        meta: ArkEmail::APIMeta,
        success: true
      }

      type data = { track_domains: ::Array[ArkEmail::TrackDomain] }

      class Data < ArkEmail::Internal::Type::BaseModel
        attr_accessor track_domains: ::Array[ArkEmail::TrackDomain]

        def initialize: (track_domains: ::Array[ArkEmail::TrackDomain]) -> void

        def to_hash: -> { track_domains: ::Array[ArkEmail::TrackDomain] }
      end
    end
  end
end
