module ArkEmail
  module Models
    type tracking_create_params =
      {
        domain_id: Integer,
        name: String,
        ssl_enabled: bool?,
        track_clicks: bool?,
        track_opens: bool?
      }
      & ArkEmail::Internal::Type::request_parameters

    class TrackingCreateParams < ArkEmail::Internal::Type::BaseModel
      extend ArkEmail::Internal::Type::RequestParameters::Converter
      include ArkEmail::Internal::Type::RequestParameters

      attr_accessor domain_id: Integer

      attr_accessor name: String

      attr_accessor ssl_enabled: bool?

      attr_accessor track_clicks: bool?

      attr_accessor track_opens: bool?

      def initialize: (
        domain_id: Integer,
        name: String,
        ?ssl_enabled: bool?,
        ?track_clicks: bool?,
        ?track_opens: bool?,
        ?request_options: ArkEmail::request_opts
      ) -> void

      def to_hash: -> {
        domain_id: Integer,
        name: String,
        ssl_enabled: bool?,
        track_clicks: bool?,
        track_opens: bool?,
        request_options: ArkEmail::RequestOptions
      }
    end
  end
end
