module ArkEmail
  module Models
    type tracking_delete_params =
      {  } & ArkEmail::Internal::Type::request_parameters

    class TrackingDeleteParams < ArkEmail::Internal::Type::BaseModel
      extend ArkEmail::Internal::Type::RequestParameters::Converter
      include ArkEmail::Internal::Type::RequestParameters

      def initialize: (?request_options: ArkEmail::request_opts) -> void

      def to_hash: -> { request_options: ArkEmail::RequestOptions }
    end
  end
end
