module ArkEmail
  module Models
    type usage_list_by_tenant_params =
      {
        limit: Integer,
        min_sent: Integer,
        offset: Integer,
        period: String,
        sort: ArkEmail::Models::UsageListByTenantParams::sort,
        status: ArkEmail::Models::UsageListByTenantParams::status,
        timezone: String
      }
      & ArkEmail::Internal::Type::request_parameters

    class UsageListByTenantParams < ArkEmail::Internal::Type::BaseModel
      extend ArkEmail::Internal::Type::RequestParameters::Converter
      include ArkEmail::Internal::Type::RequestParameters

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader min_sent: Integer?

      def min_sent=: (Integer) -> Integer

      attr_reader offset: Integer?

      def offset=: (Integer) -> Integer

      attr_reader period: String?

      def period=: (String) -> String

      attr_reader sort: ArkEmail::Models::UsageListByTenantParams::sort?

      def sort=: (
        ArkEmail::Models::UsageListByTenantParams::sort
      ) -> ArkEmail::Models::UsageListByTenantParams::sort

      attr_reader status: ArkEmail::Models::UsageListByTenantParams::status?

      def status=: (
        ArkEmail::Models::UsageListByTenantParams::status
      ) -> ArkEmail::Models::UsageListByTenantParams::status

      attr_reader timezone: String?

      def timezone=: (String) -> String

      def initialize: (
        ?limit: Integer,
        ?min_sent: Integer,
        ?offset: Integer,
        ?period: String,
        ?sort: ArkEmail::Models::UsageListByTenantParams::sort,
        ?status: ArkEmail::Models::UsageListByTenantParams::status,
        ?timezone: String,
        ?request_options: ArkEmail::request_opts
      ) -> void

      def to_hash: -> {
        limit: Integer,
        min_sent: Integer,
        offset: Integer,
        period: String,
        sort: ArkEmail::Models::UsageListByTenantParams::sort,
        status: ArkEmail::Models::UsageListByTenantParams::status,
        timezone: String,
        request_options: ArkEmail::RequestOptions
      }

      type sort =
        :sent
        | :"-sent"
        | :delivered
        | :"-delivered"
        | :bounce_rate
        | :"-bounce_rate"
        | :name
        | :"-name"

      module Sort
        extend ArkEmail::Internal::Type::Enum

        SENT: :sent
        MINUS_SENT: :"-sent"
        DELIVERED: :delivered
        MINUS_DELIVERED: :"-delivered"
        BOUNCE_RATE: :bounce_rate
        MINUS_BOUNCE_RATE: :"-bounce_rate"
        NAME: :name
        MINUS_NAME: :"-name"

        def self?.values: -> ::Array[ArkEmail::Models::UsageListByTenantParams::sort]
      end

      type status = :active | :suspended | :archived

      module Status
        extend ArkEmail::Internal::Type::Enum

        ACTIVE: :active
        SUSPENDED: :suspended
        ARCHIVED: :archived

        def self?.values: -> ::Array[ArkEmail::Models::UsageListByTenantParams::status]
      end
    end
  end
end
