module ArkEmail
  module Models
    type usage_export_params =
      {
        format_: ArkEmail::Models::UsageExportParams::format_,
        min_sent: Integer,
        period: String,
        status: ArkEmail::Models::UsageExportParams::status,
        timezone: String
      }
      & ArkEmail::Internal::Type::request_parameters

    class UsageExportParams < ArkEmail::Internal::Type::BaseModel
      extend ArkEmail::Internal::Type::RequestParameters::Converter
      include ArkEmail::Internal::Type::RequestParameters

      attr_reader format_: ArkEmail::Models::UsageExportParams::format_?

      def format_=: (
        ArkEmail::Models::UsageExportParams::format_
      ) -> ArkEmail::Models::UsageExportParams::format_

      attr_reader min_sent: Integer?

      def min_sent=: (Integer) -> Integer

      attr_reader period: String?

      def period=: (String) -> String

      attr_reader status: ArkEmail::Models::UsageExportParams::status?

      def status=: (
        ArkEmail::Models::UsageExportParams::status
      ) -> ArkEmail::Models::UsageExportParams::status

      attr_reader timezone: String?

      def timezone=: (String) -> String

      def initialize: (
        ?format_: ArkEmail::Models::UsageExportParams::format_,
        ?min_sent: Integer,
        ?period: String,
        ?status: ArkEmail::Models::UsageExportParams::status,
        ?timezone: String,
        ?request_options: ArkEmail::request_opts
      ) -> void

      def to_hash: -> {
        format_: ArkEmail::Models::UsageExportParams::format_,
        min_sent: Integer,
        period: String,
        status: ArkEmail::Models::UsageExportParams::status,
        timezone: String,
        request_options: ArkEmail::RequestOptions
      }

      type format_ = :csv | :jsonl | :json

      module Format
        extend ArkEmail::Internal::Type::Enum

        CSV: :csv
        JSONL: :jsonl
        JSON: :json

        def self?.values: -> ::Array[ArkEmail::Models::UsageExportParams::format_]
      end

      type status = :active | :suspended | :archived

      module Status
        extend ArkEmail::Internal::Type::Enum

        ACTIVE: :active
        SUSPENDED: :suspended
        ARCHIVED: :archived

        def self?.values: -> ::Array[ArkEmail::Models::UsageExportParams::status]
      end
    end
  end
end
