module ArkEmail
  module Models
    type usage_retrieve_tenant_timeseries_response =
      {
        data: ArkEmail::TenantUsageTimeseries,
        meta: ArkEmail::APIMeta,
        success: true
      }

    class UsageRetrieveTenantTimeseriesResponse < ArkEmail::Internal::Type::BaseModel
      attr_accessor data: ArkEmail::TenantUsageTimeseries

      attr_accessor meta: ArkEmail::APIMeta

      attr_accessor success: true

      def initialize: (
        data: ArkEmail::TenantUsageTimeseries,
        meta: ArkEmail::APIMeta,
        ?success: true
      ) -> void

      def to_hash: -> {
        data: ArkEmail::TenantUsageTimeseries,
        meta: ArkEmail::APIMeta,
        success: true
      }
    end
  end
end
