module ArkEmail
  module Models
    type usage_retrieve_response =
      { data: ArkEmail::LimitsData, meta: ArkEmail::APIMeta, success: true }

    class UsageRetrieveResponse < ArkEmail::Internal::Type::BaseModel
      attr_accessor data: ArkEmail::LimitsData

      attr_accessor meta: ArkEmail::APIMeta

      attr_accessor success: true

      def initialize: (
        data: ArkEmail::LimitsData,
        meta: ArkEmail::APIMeta,
        ?success: true
      ) -> void

      def to_hash: -> {
        data: ArkEmail::LimitsData,
        meta: ArkEmail::APIMeta,
        success: true
      }
    end
  end
end
