module ArkEmail
  module Models
    type usage_retrieve_tenant_usage_params =
      { period: String, timezone: String }
      & ArkEmail::Internal::Type::request_parameters

    class UsageRetrieveTenantUsageParams < ArkEmail::Internal::Type::BaseModel
      extend ArkEmail::Internal::Type::RequestParameters::Converter
      include ArkEmail::Internal::Type::RequestParameters

      attr_reader period: String?

      def period=: (String) -> String

      attr_reader timezone: String?

      def timezone=: (String) -> String

      def initialize: (
        ?period: String,
        ?timezone: String,
        ?request_options: ArkEmail::request_opts
      ) -> void

      def to_hash: -> {
        period: String,
        timezone: String,
        request_options: ArkEmail::RequestOptions
      }
    end
  end
end
