module ArkEmail
  module Models
    type webhook_update_params =
      {
        all_events: bool,
        enabled: bool,
        events: ::Array[String],
        name: String,
        url: String
      }
      & ArkEmail::Internal::Type::request_parameters

    class WebhookUpdateParams < ArkEmail::Internal::Type::BaseModel
      extend ArkEmail::Internal::Type::RequestParameters::Converter
      include ArkEmail::Internal::Type::RequestParameters

      attr_reader all_events: bool?

      def all_events=: (bool) -> bool

      attr_reader enabled: bool?

      def enabled=: (bool) -> bool

      attr_reader events: ::Array[String]?

      def events=: (::Array[String]) -> ::Array[String]

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader url: String?

      def url=: (String) -> String

      def initialize: (
        ?all_events: bool,
        ?enabled: bool,
        ?events: ::Array[String],
        ?name: String,
        ?url: String,
        ?request_options: ArkEmail::request_opts
      ) -> void

      def to_hash: -> {
        all_events: bool,
        enabled: bool,
        events: ::Array[String],
        name: String,
        url: String,
        request_options: ArkEmail::RequestOptions
      }
    end
  end
end
