module ArkEmail
  module Models
    type webhook_list_deliveries_response =
      {
        data: ::Array[ArkEmail::Models::WebhookListDeliveriesResponse::Data],
        meta: ArkEmail::APIMeta,
        page: Integer,
        per_page: Integer,
        total: Integer,
        total_pages: Integer
      }

    class WebhookListDeliveriesResponse < ArkEmail::Internal::Type::BaseModel
      attr_accessor data: ::Array[ArkEmail::Models::WebhookListDeliveriesResponse::Data]

      attr_accessor meta: ArkEmail::APIMeta

      attr_accessor page: Integer

      attr_accessor per_page: Integer

      attr_accessor total: Integer

      attr_accessor total_pages: Integer

      def initialize: (
        data: ::Array[ArkEmail::Models::WebhookListDeliveriesResponse::Data],
        meta: ArkEmail::APIMeta,
        page: Integer,
        per_page: Integer,
        total: Integer,
        total_pages: Integer
      ) -> void

      def to_hash: -> {
        data: ::Array[ArkEmail::Models::WebhookListDeliveriesResponse::Data],
        meta: ArkEmail::APIMeta,
        page: Integer,
        per_page: Integer,
        total: Integer,
        total_pages: Integer
      }

      type data =
        {
          id: String,
          attempt: Integer,
          event: ArkEmail::Models::WebhookListDeliveriesResponse::Data::event,
          status_code: Integer?,
          success: bool,
          timestamp: Time,
          url: String,
          webhook_id: String,
          will_retry: bool
        }

      class Data < ArkEmail::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor attempt: Integer

        attr_accessor event: ArkEmail::Models::WebhookListDeliveriesResponse::Data::event

        attr_accessor status_code: Integer?

        attr_accessor success: bool

        attr_accessor timestamp: Time

        attr_accessor url: String

        attr_accessor webhook_id: String

        attr_accessor will_retry: bool

        def initialize: (
          id: String,
          attempt: Integer,
          event: ArkEmail::Models::WebhookListDeliveriesResponse::Data::event,
          status_code: Integer?,
          success: bool,
          timestamp: Time,
          url: String,
          webhook_id: String,
          will_retry: bool
        ) -> void

        def to_hash: -> {
          id: String,
          attempt: Integer,
          event: ArkEmail::Models::WebhookListDeliveriesResponse::Data::event,
          status_code: Integer?,
          success: bool,
          timestamp: Time,
          url: String,
          webhook_id: String,
          will_retry: bool
        }

        type event =
          :MessageSent
          | :MessageDelayed
          | :MessageDeliveryFailed
          | :MessageHeld
          | :MessageBounced
          | :MessageLinkClicked
          | :MessageLoaded
          | :DomainDNSError
          | :SendLimitApproaching
          | :SendLimitExceeded

        module Event
          extend ArkEmail::Internal::Type::Enum

          MESSAGE_SENT: :MessageSent
          MESSAGE_DELAYED: :MessageDelayed
          MESSAGE_DELIVERY_FAILED: :MessageDeliveryFailed
          MESSAGE_HELD: :MessageHeld
          MESSAGE_BOUNCED: :MessageBounced
          MESSAGE_LINK_CLICKED: :MessageLinkClicked
          MESSAGE_LOADED: :MessageLoaded
          DOMAIN_DNS_ERROR: :DomainDNSError
          SEND_LIMIT_APPROACHING: :SendLimitApproaching
          SEND_LIMIT_EXCEEDED: :SendLimitExceeded

          def self?.values: -> ::Array[ArkEmail::Models::WebhookListDeliveriesResponse::Data::event]
        end
      end
    end
  end
end
