module ArkEmail
  module Models
    type webhook_create_params =
      {
        name: String,
        url: String,
        all_events: bool?,
        enabled: bool?,
        events: ::Array[ArkEmail::Models::WebhookCreateParams::event]?
      }
      & ArkEmail::Internal::Type::request_parameters

    class WebhookCreateParams < ArkEmail::Internal::Type::BaseModel
      extend ArkEmail::Internal::Type::RequestParameters::Converter
      include ArkEmail::Internal::Type::RequestParameters

      attr_accessor name: String

      attr_accessor url: String

      attr_accessor all_events: bool?

      attr_accessor enabled: bool?

      attr_accessor events: ::Array[ArkEmail::Models::WebhookCreateParams::event]?

      def initialize: (
        name: String,
        url: String,
        ?all_events: bool?,
        ?enabled: bool?,
        ?events: ::Array[ArkEmail::Models::WebhookCreateParams::event]?,
        ?request_options: ArkEmail::request_opts
      ) -> void

      def to_hash: -> {
        name: String,
        url: String,
        all_events: bool?,
        enabled: bool?,
        events: ::Array[ArkEmail::Models::WebhookCreateParams::event]?,
        request_options: ArkEmail::RequestOptions
      }

      type event =
        :MessageSent
        | :MessageDelayed
        | :MessageDeliveryFailed
        | :MessageHeld
        | :MessageBounced
        | :MessageLinkClicked
        | :MessageLoaded
        | :DomainDNSError

      module Event
        extend ArkEmail::Internal::Type::Enum

        MESSAGE_SENT: :MessageSent
        MESSAGE_DELAYED: :MessageDelayed
        MESSAGE_DELIVERY_FAILED: :MessageDeliveryFailed
        MESSAGE_HELD: :MessageHeld
        MESSAGE_BOUNCED: :MessageBounced
        MESSAGE_LINK_CLICKED: :MessageLinkClicked
        MESSAGE_LOADED: :MessageLoaded
        DOMAIN_DNS_ERROR: :DomainDNSError

        def self?.values: -> ::Array[ArkEmail::Models::WebhookCreateParams::event]
      end
    end
  end
end
