module ArkEmail
  module Models
    type webhook_update_params =
      {
        all_events: bool?,
        enabled: bool?,
        events: ::Array[String]?,
        name: String?,
        url: String?
      }
      & ArkEmail::Internal::Type::request_parameters

    class WebhookUpdateParams < ArkEmail::Internal::Type::BaseModel
      extend ArkEmail::Internal::Type::RequestParameters::Converter
      include ArkEmail::Internal::Type::RequestParameters

      attr_accessor all_events: bool?

      attr_accessor enabled: bool?

      attr_accessor events: ::Array[String]?

      attr_accessor name: String?

      attr_accessor url: String?

      def initialize: (
        ?all_events: bool?,
        ?enabled: bool?,
        ?events: ::Array[String]?,
        ?name: String?,
        ?url: String?,
        ?request_options: ArkEmail::request_opts
      ) -> void

      def to_hash: -> {
        all_events: bool?,
        enabled: bool?,
        events: ::Array[String]?,
        name: String?,
        url: String?,
        request_options: ArkEmail::RequestOptions
      }
    end
  end
end
