module ArkEmail
  module Resources
    class Tenants
      class Credentials
        def create: (
          String tenant_id,
          name: String,
          type: ArkEmail::Models::Tenants::CredentialCreateParams::type_,
          ?request_options: ArkEmail::request_opts
        ) -> ArkEmail::Models::Tenants::CredentialCreateResponse

        def retrieve: (
          Integer credential_id,
          tenant_id: String,
          ?reveal: bool,
          ?request_options: ArkEmail::request_opts
        ) -> ArkEmail::Models::Tenants::CredentialRetrieveResponse

        def update: (
          Integer credential_id,
          tenant_id: String,
          ?hold: bool,
          ?name: String,
          ?request_options: ArkEmail::request_opts
        ) -> ArkEmail::Models::Tenants::CredentialUpdateResponse

        def list: (
          String tenant_id,
          ?page: Integer,
          ?per_page: Integer,
          ?type: ArkEmail::Models::Tenants::CredentialListParams::type_,
          ?request_options: ArkEmail::request_opts
        ) -> ArkEmail::Internal::PageNumberPagination[ArkEmail::Models::Tenants::CredentialListResponse]

        def delete: (
          Integer credential_id,
          tenant_id: String,
          ?request_options: ArkEmail::request_opts
        ) -> ArkEmail::Models::Tenants::CredentialDeleteResponse

        def initialize: (client: ArkEmail::Client) -> void
      end
    end
  end
end
