module ArkEmail
  module Models
    module Tenants
      type credential_update_params =
        { tenant_id: String, hold: bool, name: String }
        & ArkEmail::Internal::Type::request_parameters

      class CredentialUpdateParams < ArkEmail::Internal::Type::BaseModel
        extend ArkEmail::Internal::Type::RequestParameters::Converter
        include ArkEmail::Internal::Type::RequestParameters

        attr_accessor tenant_id: String

        attr_reader hold: bool?

        def hold=: (bool) -> bool

        attr_reader name: String?

        def name=: (String) -> String

        def initialize: (
          tenant_id: String,
          ?hold: bool,
          ?name: String,
          ?request_options: ArkEmail::request_opts
        ) -> void

        def to_hash: -> {
          tenant_id: String,
          hold: bool,
          name: String,
          request_options: ArkEmail::RequestOptions
        }
      end
    end
  end
end
