module ArkEmail
  module Models
    module Tenants
      type credential_create_params =
        {
          name: String,
          type: ArkEmail::Models::Tenants::CredentialCreateParams::type_
        }
        & ArkEmail::Internal::Type::request_parameters

      class CredentialCreateParams < ArkEmail::Internal::Type::BaseModel
        extend ArkEmail::Internal::Type::RequestParameters::Converter
        include ArkEmail::Internal::Type::RequestParameters

        attr_accessor name: String

        attr_accessor type: ArkEmail::Models::Tenants::CredentialCreateParams::type_

        def initialize: (
          name: String,
          type: ArkEmail::Models::Tenants::CredentialCreateParams::type_,
          ?request_options: ArkEmail::request_opts
        ) -> void

        def to_hash: -> {
          name: String,
          type: ArkEmail::Models::Tenants::CredentialCreateParams::type_,
          request_options: ArkEmail::RequestOptions
        }

        type type_ = :smtp | :api

        module Type
          extend ArkEmail::Internal::Type::Enum

          SMTP: :smtp
          API: :api

          def self?.values: -> ::Array[ArkEmail::Models::Tenants::CredentialCreateParams::type_]
        end
      end
    end
  end
end
