module ArkEmail
  module Models
    module Tenants
      type credential_delete_response =
        {
          data: ArkEmail::Models::Tenants::CredentialDeleteResponse::Data,
          meta: ArkEmail::APIMeta,
          success: true
        }

      class CredentialDeleteResponse < ArkEmail::Internal::Type::BaseModel
        attr_accessor data: ArkEmail::Models::Tenants::CredentialDeleteResponse::Data

        attr_accessor meta: ArkEmail::APIMeta

        attr_accessor success: true

        def initialize: (
          data: ArkEmail::Models::Tenants::CredentialDeleteResponse::Data,
          meta: ArkEmail::APIMeta,
          ?success: true
        ) -> void

        def to_hash: -> {
          data: ArkEmail::Models::Tenants::CredentialDeleteResponse::Data,
          meta: ArkEmail::APIMeta,
          success: true
        }

        type data = { deleted: true }

        class Data < ArkEmail::Internal::Type::BaseModel
          attr_accessor deleted: true

          def initialize: (?deleted: true) -> void

          def to_hash: -> { deleted: true }
        end
      end
    end
  end
end
