module ArkEmail
  module Models
    module Tenants
      type credential_retrieve_params =
        { tenant_id: String, reveal: bool }
        & ArkEmail::Internal::Type::request_parameters

      class CredentialRetrieveParams < ArkEmail::Internal::Type::BaseModel
        extend ArkEmail::Internal::Type::RequestParameters::Converter
        include ArkEmail::Internal::Type::RequestParameters

        attr_accessor tenant_id: String

        attr_reader reveal: bool?

        def reveal=: (bool) -> bool

        def initialize: (
          tenant_id: String,
          ?reveal: bool,
          ?request_options: ArkEmail::request_opts
        ) -> void

        def to_hash: -> {
          tenant_id: String,
          reveal: bool,
          request_options: ArkEmail::RequestOptions
        }
      end
    end
  end
end
