module ArkEmail
  module Models
    module Tenants
      type credential_list_params =
        {
          page: Integer,
          per_page: Integer,
          type: ArkEmail::Models::Tenants::CredentialListParams::type_
        }
        & ArkEmail::Internal::Type::request_parameters

      class CredentialListParams < ArkEmail::Internal::Type::BaseModel
        extend ArkEmail::Internal::Type::RequestParameters::Converter
        include ArkEmail::Internal::Type::RequestParameters

        attr_reader page: Integer?

        def page=: (Integer) -> Integer

        attr_reader per_page: Integer?

        def per_page=: (Integer) -> Integer

        attr_reader type: ArkEmail::Models::Tenants::CredentialListParams::type_?

        def type=: (
          ArkEmail::Models::Tenants::CredentialListParams::type_
        ) -> ArkEmail::Models::Tenants::CredentialListParams::type_

        def initialize: (
          ?page: Integer,
          ?per_page: Integer,
          ?type: ArkEmail::Models::Tenants::CredentialListParams::type_,
          ?request_options: ArkEmail::request_opts
        ) -> void

        def to_hash: -> {
          page: Integer,
          per_page: Integer,
          type: ArkEmail::Models::Tenants::CredentialListParams::type_,
          request_options: ArkEmail::RequestOptions
        }

        type type_ = :smtp | :api

        module Type
          extend ArkEmail::Internal::Type::Enum

          SMTP: :smtp
          API: :api

          def self?.values: -> ::Array[ArkEmail::Models::Tenants::CredentialListParams::type_]
        end
      end
    end
  end
end
