module ArkEmail
  module Models
    module Tenants
      type credential_delete_params =
        { tenant_id: String, credential_id: Integer }
        & ArkEmail::Internal::Type::request_parameters

      class CredentialDeleteParams < ArkEmail::Internal::Type::BaseModel
        extend ArkEmail::Internal::Type::RequestParameters::Converter
        include ArkEmail::Internal::Type::RequestParameters

        attr_accessor tenant_id: String

        attr_accessor credential_id: Integer

        def initialize: (
          tenant_id: String,
          credential_id: Integer,
          ?request_options: ArkEmail::request_opts
        ) -> void

        def to_hash: -> {
          tenant_id: String,
          credential_id: Integer,
          request_options: ArkEmail::RequestOptions
        }
      end
    end
  end
end
