module ArkEmail
  module Models
    module Tenants
      type credential_create_response =
        {
          data: ArkEmail::Models::Tenants::CredentialCreateResponse::Data,
          meta: ArkEmail::APIMeta,
          success: true
        }

      class CredentialCreateResponse < ArkEmail::Internal::Type::BaseModel
        attr_accessor data: ArkEmail::Models::Tenants::CredentialCreateResponse::Data

        attr_accessor meta: ArkEmail::APIMeta

        attr_accessor success: true

        def initialize: (
          data: ArkEmail::Models::Tenants::CredentialCreateResponse::Data,
          meta: ArkEmail::APIMeta,
          ?success: true
        ) -> void

        def to_hash: -> {
          data: ArkEmail::Models::Tenants::CredentialCreateResponse::Data,
          meta: ArkEmail::APIMeta,
          success: true
        }

        type data =
          {
            id: Integer,
            created_at: Time,
            hold: bool,
            key: String,
            last_used_at: Time?,
            name: String,
            type: ArkEmail::Models::Tenants::CredentialCreateResponse::Data::type_,
            updated_at: Time,
            smtp_username: String
          }

        class Data < ArkEmail::Internal::Type::BaseModel
          attr_accessor id: Integer

          attr_accessor created_at: Time

          attr_accessor hold: bool

          attr_accessor key: String

          attr_accessor last_used_at: Time?

          attr_accessor name: String

          attr_accessor type: ArkEmail::Models::Tenants::CredentialCreateResponse::Data::type_

          attr_accessor updated_at: Time

          attr_reader smtp_username: String?

          def smtp_username=: (String) -> String

          def initialize: (
            id: Integer,
            created_at: Time,
            hold: bool,
            key: String,
            last_used_at: Time?,
            name: String,
            type: ArkEmail::Models::Tenants::CredentialCreateResponse::Data::type_,
            updated_at: Time,
            ?smtp_username: String
          ) -> void

          def to_hash: -> {
            id: Integer,
            created_at: Time,
            hold: bool,
            key: String,
            last_used_at: Time?,
            name: String,
            type: ArkEmail::Models::Tenants::CredentialCreateResponse::Data::type_,
            updated_at: Time,
            smtp_username: String
          }

          type type_ = :smtp | :api

          module Type
            extend ArkEmail::Internal::Type::Enum

            SMTP: :smtp
            API: :api

            def self?.values: -> ::Array[ArkEmail::Models::Tenants::CredentialCreateResponse::Data::type_]
          end
        end
      end
    end
  end
end
