module ArkEmail
  module Models
    module Tenants
      type domain_list_response =
        {
          data: ArkEmail::Models::Tenants::DomainListResponse::Data,
          meta: ArkEmail::APIMeta,
          success: true
        }

      class DomainListResponse < ArkEmail::Internal::Type::BaseModel
        attr_accessor data: ArkEmail::Models::Tenants::DomainListResponse::Data

        attr_accessor meta: ArkEmail::APIMeta

        attr_accessor success: true

        def initialize: (
          data: ArkEmail::Models::Tenants::DomainListResponse::Data,
          meta: ArkEmail::APIMeta,
          ?success: true
        ) -> void

        def to_hash: -> {
          data: ArkEmail::Models::Tenants::DomainListResponse::Data,
          meta: ArkEmail::APIMeta,
          success: true
        }

        type data =
          {
            domains: ::Array[ArkEmail::Models::Tenants::DomainListResponse::Data::Domain]
          }

        class Data < ArkEmail::Internal::Type::BaseModel
          attr_accessor domains: ::Array[ArkEmail::Models::Tenants::DomainListResponse::Data::Domain]

          def initialize: (
            domains: ::Array[ArkEmail::Models::Tenants::DomainListResponse::Data::Domain]
          ) -> void

          def to_hash: -> {
            domains: ::Array[ArkEmail::Models::Tenants::DomainListResponse::Data::Domain]
          }

          type domain =
            {
              id: Integer,
              name: String,
              verified: bool,
              tenant_id: String,
              tenant_name: String
            }

          class Domain < ArkEmail::Internal::Type::BaseModel
            attr_accessor id: Integer

            attr_accessor name: String

            attr_accessor verified: bool

            attr_reader tenant_id: String?

            def tenant_id=: (String) -> String

            attr_reader tenant_name: String?

            def tenant_name=: (String) -> String

            def initialize: (
              id: Integer,
              name: String,
              verified: bool,
              ?tenant_id: String,
              ?tenant_name: String
            ) -> void

            def to_hash: -> {
              id: Integer,
              name: String,
              verified: bool,
              tenant_id: String,
              tenant_name: String
            }
          end
        end
      end
    end
  end
end
