module ArkEmail
  module Models
    module Tenants
      type suppression_delete_params =
        { tenant_id: String, email: String }
        & ArkEmail::Internal::Type::request_parameters

      class SuppressionDeleteParams < ArkEmail::Internal::Type::BaseModel
        extend ArkEmail::Internal::Type::RequestParameters::Converter
        include ArkEmail::Internal::Type::RequestParameters

        attr_accessor tenant_id: String

        attr_accessor email: String

        def initialize: (
          tenant_id: String,
          email: String,
          ?request_options: ArkEmail::request_opts
        ) -> void

        def to_hash: -> {
          tenant_id: String,
          email: String,
          request_options: ArkEmail::RequestOptions
        }
      end
    end
  end
end
